apiVersion: v1
kind: Pod
metadata:
  name: notification
  namespace: appcenter
  labels:
    name: notification
spec:
  containers:
    - name: notification
      image: quay.ac.uda.io/appcenter/notification-service
      env:
        - name: DATASOURCE_METADATA_JDBCURL
          value: "jdbc:postgresql://172.17.0.1:5432/metadata"
        - name: DATASOURCE_METADATA_USER
          value: postgres
        - name: DATASOURCE_METADATA_PASSWORD
          value: postgres
        - name: SPRING_CLOUD_CONSUL_HOST
          value: "172.17.0.1"
        - name: SPRING_CLOUD_CONSUL_DISCOVERY_HEALTH_CHECK_URL
          value: "http://172.17.0.1:8006/health"
        - name: LOGSTR
          value: "notification_service 1.0"
        - name: SERVER_PORT
          value: "8006"
        - name: AUDIT_SERVICE_MESSAGE_URL
          value: "http://172.17.0.1:8005/audit/messages"
        - name: USER_SERVICE_AUTHENTICATION_URL
          value: "http://172.17.0.1:8001/token"
      ports:
        - containerPort: 8006
          hostPort: 8006
