# Copyright 2018 bad_db. All rights reserved.
# tddb CONFIDENTIAL AND TRADE SECRET

- name: include variables from groups_vars/startvars
  include_vars:
    file: ../../../inventory/group_vars/startvars.yml

- name: include resource request values
  include_vars:
    file: ../../../inventory/group_vars/resources_{{ PLATFORM }}.yml

- name: check if localPath is defined 
  stat: 
    path: "{{ localPath }}"
  register: localDir

- fail:
    msg: "localPath is either undefined or not a directory.
          Please provide the path where you want metadata tar file to get exported as an input in extravars."
  when: localDir.stat.isdir is not defined or not localDir.stat.isdir

- name: render yaml.preNamespace configs
  template: src=etc/aster/manifests/{{ item }}.yaml.j2 dest={{ role_path }}/templates/etc/aster/manifests/{{ item }}.yaml.preNamespace
  with_items:
    - mleimportupgrade-pod

- name: start kube proxy
  local_action: shell {{ role_path }}/files/etc/aster/manifests/kubeProxy.sh start {{ hostvars[groups['aster_local'][0]].kubeconfig }}
  register: proxyvar

- name: existing proxy message
  debug:
    msg:
      - "Using existing proxy with remote-kubeconfig:"
      - "{{ proxyvar.stdout }}"
  when: proxyvar.stdout.find("KUBECONFIG") != -1

- name: update namespaces
  local_action: shell {{ role_path }}/files/etc/aster/manifests/updateNamespaces.sh {{ CLUSTER_NAME }} {{ role_path }}/templates/etc/aster/manifests/
  ignore_errors: no

- name: update remote registry info in pod definitions
  local_action: shell {{ role_path }}/files/etc/aster/manifests/updateRegistryInfo.sh {{ role_path }}/templates/etc/aster/manifests/   {{ USE_LOCAL_REGISTRY }} {{ DOCKER_REPO_HOST }} {{ DOCKER_REPO_PORT }} {{ DOCKER_REPO_PATH }} {{ DOCKER_REPO_TAG }}
  when: USE_REMOTE_REGISTRY
  ignore_errors: no

- name: create mleimportupdate
  local_action: shell kubectl create -f {{ role_path }}/templates/etc/aster/manifests/mleimportupgrade-pod.yaml
  ignore_errors: no

- name: check importpod status
  local_action: shell {{ role_path }}/files/etc/aster/manifests/waitForImportPod.sh {{ CLUSTER_NAME }}
  ignore_errors: no

- name: copy exported files from controller node to the container
  local_action: shell kubectl cp {{ localPath }}/{{ tarfile }} upgradeimport:/home/beehive/mle_upgrade_backup/ -c mle-metadata-import -n {{ CLUSTER_NAME }}
  ignore_errors: no

- name: Inform the pod that metadata is available for importing
  local_action: shell cp {{ localPath }}/{{ hashfile }} kcpDone && kubectl cp kcpDone upgradeimport:/tmp/ -c mle-metadata-import -n {{ CLUSTER_NAME }} && rm kcpDone
  ignore_errors: no

- name: Copy import logs to controller machine
  local_action: shell {{ role_path }}/files/etc/aster/manifests/copyLogs.sh {{ CLUSTER_NAME }} {{ localPath }}
  ignore_errors: no

- name: delete importpod
  local_action: shell {{ role_path }}/files/etc/aster/manifests/deleteImportPod.sh {{ CLUSTER_NAME }} {{ role_path }}/templates/etc/aster/manifests/mleimportupgrade-pod.yaml
  ignore_errors: no

- name: stop proxy
  local_action: shell {{ role_path }}/files/etc/aster/manifests/kubeProxy.sh stop {{ proxyvar.stdout }}
  when: proxyvar.stdout.find("KUBECONFIG") == -1
