apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: cloud-platform
  labels:
    name: registry
spec:
  containers:
    - name: registry
      image: quay.ac.uda.io/library/registry:2.3
      env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
      ports:
        - containerPort: 5000
          hostPort: 5001
