# Copyright 2018 bad_db. All rights reserved.
# tddb CONFIDENTIAL AND TRADE SECRET
#
# Aster cleanup script 
# 
# To use execute following command:
# ansible-playbook --inventory-file=./inventory/inventory.local -u root --ask-pass cleanup.yml -vvvv

- hosts: kube-aster
  roles:
    - { role: cleanup, tags: cleanup}
