# Copyright (c) 2018 by bad_db Corporation. All rights reserved.
# tddb CORPORATION CONFIDENTIAL AND TRADE SECRET
#
# delete Aster
# 
# To use execute following command:
# ansible-playbook --inventory-file=./inventory/inventory.local -u root --ask-pass deleteaster.yml

- hosts: aster_local
  roles:
    - { role: deleteaster, mode: deleteK8S, tags: deleteaster}
  environment:
    - KUBECTL: "kubectl --kubeconfig={{ hostvars[inventory_hostname].kubeconfig }}"


- hosts: kube_aster
  roles:
    - { role: deleteaster, mode: deleteImages, tags: deleteaster}
