apiVersion: v1 
kind: Pod 
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
spec:
  containers:
  - name: filebeat
    image: quay.ac.uda.io/appcenter/filebeat-kubernetes:v0.2 
    resources:
       limits:
         cpu: 50m
         memory: 50Mi
    env:
    - name: LOGSTASH_HOSTS
      value: "'172.17.0.1:5000'"
    - name: LOG_LEVEL
      value: info
    volumeMounts:
    - name: varlog
      mountPath: /var/log/containers
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  terminationGracePeriodSeconds: 30
  volumes:
  - name: varlog
    hostPath:
      path: /var/log/containers
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
