kind: Pod
apiVersion: v1
metadata:
  name: cockpit
spec:
  containers:
  - name: kubernetes-cockpit
    image: quay.ac.uda.io/cockpit/kubernetes:latest
    ports:
    - containerPort: 9090
      hostPort: 9091
      protocol: TCP
    env:
    - name: KUBE_INSECURE
      value: 'false'
