apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
    name: db
  - port: 5000
    protocol: TCP
    targetPort: logstash 
    name: logstash
  selector:
    k8s-app: elasticsearch-logging
